#!/usr/bin/env python
import argparse
import subprocess

def model(output, args):
    message = ' '.join(args.message)
    cmd = [
        "openscad",
        "-o", output,
        "-D", f'message="{message}"',
        "-D", f'font="{args.font}"',
        "-D", f'font_size={args.size}',
        "-D", f'depth={args.depth}',
        "stamp.scad",
    ]
    print(' '.join(cmd))
    subprocess.run(cmd)


def slice():
    cmd = [
        "Slic3r",
        "--skirts=0",
        "--temperature=215",
        "--bed-temperature=60",
        "--first-layer-bed-temperature=60",
        "--layer-height=0.15",
        "--nozzle-diameter=0.4",
        "--cooling",
        "stamp.stl",
    ]
    print(' '.join(cmd))
    subprocess.run(cmd)

parser = argparse.ArgumentParser(description='Generate a text stamp.')
parser.add_argument('-d', '--depth', default=5, help='Stamp Depth')
parser.add_argument('-s', '--size', default=10, help='Font Size')
parser.add_argument('-f', '--font', default="JMH Typewriter dry", help='Font/Style')
parser.add_argument('message', nargs='+')
args = parser.parse_args()

model('stamp.stl', args)
slice()
